apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config-map
data:
  DATABASE_URL: jdbc:mysql://mysql-service:3306/product?createDatabaseIfNotExist=true
  DATABASE_USER: root
  DATABASE_PASSWORD: root
