apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config-map
data:
  DATABASE_URL: jdbc:mysql://mysql-service:3306/user?createDatabaseIfNotExist=true
  DATABASE_USER: root
  DATABASE_PASSWORD: root
